### ISSUE TITLE
Application name contains trademarked brand name

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.github.aandrew_me.ytdn#24]
Hello we are tracking a bunch of applications with trademark violations.

The current application name contains "Youtube" which is someone else's brand name.

Please try to use your name for the application to avoid trademark issues and confusing people. I think 2 months is a reasonable time period for us to wait for the name to be changed.

You can find some resources for application names in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-name

And the guidelines on trademarks https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

**Comment by aandrew-me** [comment]
I will change it then
