### ISSUE TITLE
Wrong duration metadata for sectionwise download

### ISSUE THREAD

**Issue by Amenoph** [flathub/io.github.aandrew_me.ytdn#28]
When I specify a section, the download does what expected, but the metadata of the resulting MP4 state the full duration of the original video. It should be the duration of the section only. Thanks for the tool and for considering.

**Comment by aandrew-me** [comment]
Yes I have noticed that too, I will fix it

**Comment by aandrew-me** [comment]
I track the issues in the original repo of the project, so I am gonna close the issue here. 
Here is the new issue - https://github.com/aandrew-me/ytDownloader/issues/246
