### ISSUE TITLE
Feature request: add aarch64

### ISSUE THREAD

**Issue by theofficialgman** [flathub/io.github.aandrew_me.ytdn#4]
as the title said, I would like if this flatpak was available for aarch64. shouldn't be too hard as the yt-dlp ffmpeg builds you use already have aarch64 releases and the rest is just web technologies using electron

**Comment by aandrew-me** [comment]
> as the title said, I would like if this flatpak was available for aarch64. shouldn't be too hard as the yt-dlp ffmpeg builds you use already have aarch64 releases and the rest is just web technologies using electron

Yes I added aarch64, it should be available in next update
